In [10]:
import pandas as pd
import datetime as dt
from datetime import datetime

df = pd.read_csv('met21_23.csv', index_col=0)

In [11]:
df.head()

,date,time,wind_speed,wind_direction,wind_gust,air_temp,baro,humidity,visibility
1,5/27/2021,0:00,-,-,-,81.3,1017.9,-,-
2,5/27/2021,1:00,-,-,-,81.1,1018.6,-,-
3,5/27/2021,2:00,-,-,-,81.1,1019.1,-,-
4,5/27/2021,3:00,-,-,-,81.1,1019.2,-,-
5,5/27/2021,4:00,-,-,-,81.1,1018.8,-,-

In [14]:
df['date'] = pd.to_datetime(df["date"])

In [16]:
df['date'] = df["date"].dt.strftime('%Y-%m-%d')

In [17]:
df.head()

,date,time,wind_speed,wind_direction,wind_gust,air_temp,baro,humidity,visibility
1,2021-05-27,0:00,-,-,-,81.3,1017.9,-,-
2,2021-05-27,1:00,-,-,-,81.1,1018.6,-,-
3,2021-05-27,2:00,-,-,-,81.1,1019.1,-,-
4,2021-05-27,3:00,-,-,-,81.1,1019.2,-,-
5,2021-05-27,4:00,-,-,-,81.1,1018.8,-,-

In [19]:
df.to_csv('met21_23.csv')